// <auto-generated />
using System;
using Commtrac.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commtrac.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205030014_AddAssetsAndRoleConfigs")]
    partial class AddAssetsAndRoleConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Commtrac.Api.Data.TableConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseFieldNamesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("HiddenJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("OrderJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableName")
                        .IsUnique();

                    b.ToTable("TableConfigs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AdminTabEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryActionLabel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminTabs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AdminTabRowEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminTabRows");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AssetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PmCount")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Commtrac.Api.Models.CustomFieldDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Product")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldDefinitions");
                });

            modelBuilder.Entity("Commtrac.Api.Models.CustomerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Commtrac.Api.Models.DocumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Commtrac.Api.Models.FieldDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkToFieldId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TablesJson")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldDefinitions");

                    b.HasData(
                        new
                        {
                            Id = "field-job-number",
                            FieldType = "primary key",
                            IsActive = true,
                            Name = "Job Number",
                            SortOrder = 1,
                            TablesJson = "[\"projects\",\"installations\"]"
                        },
                        new
                        {
                            Id = "field-project-type",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Project Type",
                            SortOrder = 2,
                            TablesJson = "[\"projects\"]"
                        },
                        new
                        {
                            Id = "field-customer",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Customer",
                            SortOrder = 3,
                            TablesJson = "[\"projects\",\"customers\"]"
                        },
                        new
                        {
                            Id = "field-products",
                            FieldType = "multi-select",
                            IsActive = true,
                            Name = "Products",
                            SortOrder = 4,
                            TablesJson = "[\"projects\",\"products\"]"
                        },
                        new
                        {
                            Id = "field-status",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Status",
                            SortOrder = 5,
                            TablesJson = "[\"projects\",\"installations\",\"inspections\",\"issues\"]"
                        },
                        new
                        {
                            Id = "field-office",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Office",
                            SortOrder = 6,
                            TablesJson = "[\"projects\",\"customers\",\"users\"]"
                        },
                        new
                        {
                            Id = "field-site-name",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Site Name",
                            SortOrder = 7,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-start-date",
                            FieldType = "date",
                            IsActive = true,
                            Name = "Start Date",
                            SortOrder = 8,
                            TablesJson = "[\"installations\",\"issues\"]"
                        },
                        new
                        {
                            Id = "field-finish-date",
                            FieldType = "date",
                            IsActive = true,
                            Name = "Finish Date",
                            SortOrder = 9,
                            TablesJson = "[\"issues\"]"
                        },
                        new
                        {
                            Id = "field-progress",
                            FieldType = "percentage",
                            IsActive = true,
                            Name = "Progress",
                            SortOrder = 10,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-installer",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Installer",
                            SortOrder = 11,
                            TablesJson = "[\"installations\",\"inspections\"]"
                        },
                        new
                        {
                            Id = "field-inspector",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Inspector",
                            SortOrder = 12,
                            TablesJson = "[\"inspections\"]"
                        },
                        new
                        {
                            Id = "field-photos",
                            FieldType = "number",
                            IsActive = true,
                            Name = "Photos",
                            SortOrder = 13,
                            TablesJson = "[\"inspections\"]"
                        },
                        new
                        {
                            Id = "field-issue",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Issue",
                            SortOrder = 14,
                            TablesJson = "[\"issues\"]"
                        },
                        new
                        {
                            Id = "field-priority",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Priority",
                            SortOrder = 15,
                            TablesJson = "[\"issues\"]"
                        },
                        new
                        {
                            Id = "field-owner",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Owner",
                            SortOrder = 16,
                            TablesJson = "[\"issues\"]"
                        },
                        new
                        {
                            Id = "field-machine-type",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Machine Type",
                            SortOrder = 17,
                            TablesJson = "[\"installations\",\"assets\"]"
                        },
                        new
                        {
                            Id = "field-pm1",
                            FieldType = "text",
                            IsActive = true,
                            Name = "PM-1 S/N",
                            SortOrder = 18,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-pm2",
                            FieldType = "text",
                            IsActive = true,
                            Name = "PM-2 S/N",
                            SortOrder = 19,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-pm3",
                            FieldType = "text",
                            IsActive = true,
                            Name = "PM-3 S/N",
                            SortOrder = 20,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-pm4",
                            FieldType = "text",
                            IsActive = true,
                            Name = "PM-4 S/N",
                            SortOrder = 21,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-asset-id",
                            FieldType = "primary key",
                            IsActive = true,
                            Name = "Asset ID#",
                            SortOrder = 22,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-machine-id",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Machine ID",
                            SortOrder = 23,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-serial-number",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Serial Number",
                            SortOrder = 24,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-pm-count",
                            FieldType = "number",
                            IsActive = true,
                            Name = "PM Count",
                            SortOrder = 25,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-comments",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Comments",
                            SortOrder = 26,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-document",
                            FieldType = "file",
                            IsActive = true,
                            Name = "Document",
                            SortOrder = 27,
                            TablesJson = "[\"documents\"]"
                        },
                        new
                        {
                            Id = "field-document-type",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Document Type",
                            SortOrder = 28,
                            TablesJson = "[\"documents\"]"
                        },
                        new
                        {
                            Id = "field-linked-to",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Linked To",
                            SortOrder = 29,
                            TablesJson = "[\"documents\"]"
                        },
                        new
                        {
                            Id = "field-uploaded-at",
                            FieldType = "date",
                            IsActive = true,
                            Name = "Uploaded At",
                            SortOrder = 30,
                            TablesJson = "[\"documents\"]"
                        },
                        new
                        {
                            Id = "field-user-name",
                            FieldType = "text",
                            IsActive = true,
                            Name = "User Name",
                            SortOrder = 31,
                            TablesJson = "[\"users\"]"
                        },
                        new
                        {
                            Id = "field-email",
                            FieldType = "email",
                            IsActive = true,
                            Name = "Email",
                            SortOrder = 32,
                            TablesJson = "[\"users\"]"
                        },
                        new
                        {
                            Id = "field-role",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Role",
                            SortOrder = 33,
                            TablesJson = "[\"users\"]"
                        },
                        new
                        {
                            Id = "field-active",
                            FieldType = "checkbox",
                            IsActive = true,
                            Name = "Active",
                            SortOrder = 34,
                            TablesJson = "[\"users\"]"
                        });
                });

            modelBuilder.Entity("Commtrac.Api.Models.FieldValueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldDefinitionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldValues");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InspectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inspector")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduledDate")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InspectionPhotoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InspectionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InspectionPhotos");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InstallationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualFinish")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualStart")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUsers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("CustomerSignOffContact")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerSignOffDate")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallerNotes")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pm1Serial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pm2Serial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pm3Serial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pm4Serial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledEnd")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledStart")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteContactName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteContactPhone")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InstallationTabEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstallationTabs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InstallationTabRowEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstallationTabRows");
                });

            modelBuilder.Entity("Commtrac.Api.Models.IssueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Commtrac.Api.Models.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Commtrac.Api.Models.ProjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalDecision")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ContractValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishDate")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationMode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInstallationProject")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbabilityStage")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectManager")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Commtrac.Api.Models.QuickbaseSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationsFieldMapJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("InstallationsTableId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectsFieldMapJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("ProjectsTableId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmHostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuickbaseSettings");
                });

            modelBuilder.Entity("Commtrac.Api.Models.RoleConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleConfigs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
