// <auto-generated />
using System;
using Commtrac.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commtrac.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Commtrac.Api.Data.TableConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseFieldMetaJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("BaseFieldNamesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("HiddenJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("OrderJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableName")
                        .IsUnique();

                    b.ToTable("TableConfigs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AdminTabEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryActionLabel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminTabs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AdminTabRowEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminTabRows");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AssetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PmCount")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AssetWorkflowAssignmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowConfigId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowTypeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("WorkflowConfigId");

                    b.ToTable("AssetWorkflowAssignments");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AssetWorkflowRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedByName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("RunNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepResultsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("TechnicianUserId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowConfigId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowSnapshotJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("WorkflowConfigId");

                    b.ToTable("AssetWorkflowRuns");
                });

            modelBuilder.Entity("Commtrac.Api.Models.AuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.BrandSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("BrandSettings");
                });

            modelBuilder.Entity("Commtrac.Api.Models.CustomFieldDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Product")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldDefinitions");
                });

            modelBuilder.Entity("Commtrac.Api.Models.CustomerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoShape")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("LogoSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoScale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Commtrac.Api.Models.DocumentConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TabsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentConfigs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.DocumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Commtrac.Api.Models.FieldDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkToFieldId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TablesJson")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldDefinitions");

                    b.HasData(
                        new
                        {
                            Id = "field-job-number",
                            FieldType = "primary key",
                            IsActive = true,
                            Name = "Job Number",
                            SortOrder = 1,
                            TablesJson = "[\"projects\",\"installations\"]"
                        },
                        new
                        {
                            Id = "field-project-type",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Project Type",
                            SortOrder = 2,
                            TablesJson = "[\"projects\"]"
                        },
                        new
                        {
                            Id = "field-customer",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Customer",
                            SortOrder = 3,
                            TablesJson = "[\"projects\",\"customers\"]"
                        },
                        new
                        {
                            Id = "field-products",
                            FieldType = "multi-select",
                            IsActive = true,
                            Name = "Products",
                            SortOrder = 4,
                            TablesJson = "[\"projects\",\"products\"]"
                        },
                        new
                        {
                            Id = "field-status",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Status",
                            SortOrder = 5,
                            TablesJson = "[\"projects\",\"installations\",\"inspections\",\"issues\"]"
                        },
                        new
                        {
                            Id = "field-office",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Global Offices",
                            SortOrder = 6,
                            TablesJson = "[\"projects\",\"customers\",\"users\"]"
                        },
                        new
                        {
                            Id = "field-site-name",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Site Name",
                            SortOrder = 7,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-start-date",
                            FieldType = "date",
                            IsActive = true,
                            Name = "Start Date",
                            SortOrder = 8,
                            TablesJson = "[\"installations\",\"issues\"]"
                        },
                        new
                        {
                            Id = "field-finish-date",
                            FieldType = "date",
                            IsActive = true,
                            Name = "Finish Date",
                            SortOrder = 9,
                            TablesJson = "[\"issues\"]"
                        },
                        new
                        {
                            Id = "field-progress",
                            FieldType = "percentage",
                            IsActive = true,
                            Name = "Progress",
                            SortOrder = 10,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-installer",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Installer",
                            SortOrder = 11,
                            TablesJson = "[\"installations\",\"inspections\"]"
                        },
                        new
                        {
                            Id = "field-inspector",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Inspector",
                            SortOrder = 12,
                            TablesJson = "[\"inspections\"]"
                        },
                        new
                        {
                            Id = "field-photos",
                            FieldType = "number",
                            IsActive = true,
                            Name = "Photos",
                            SortOrder = 13,
                            TablesJson = "[\"inspections\"]"
                        },
                        new
                        {
                            Id = "field-issue",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Issue",
                            SortOrder = 14,
                            TablesJson = "[\"issues\"]"
                        },
                        new
                        {
                            Id = "field-priority",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Priority",
                            SortOrder = 15,
                            TablesJson = "[\"issues\"]"
                        },
                        new
                        {
                            Id = "field-owner",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Owner",
                            SortOrder = 16,
                            TablesJson = "[\"issues\"]"
                        },
                        new
                        {
                            Id = "field-machine-type",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Machine Type",
                            SortOrder = 17,
                            TablesJson = "[\"installations\",\"assets\"]"
                        },
                        new
                        {
                            Id = "field-pm1",
                            FieldType = "text",
                            IsActive = true,
                            Name = "PM-1 S/N",
                            SortOrder = 18,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-pm2",
                            FieldType = "text",
                            IsActive = true,
                            Name = "PM-2 S/N",
                            SortOrder = 19,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-pm3",
                            FieldType = "text",
                            IsActive = true,
                            Name = "PM-3 S/N",
                            SortOrder = 20,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-pm4",
                            FieldType = "text",
                            IsActive = true,
                            Name = "PM-4 S/N",
                            SortOrder = 21,
                            TablesJson = "[\"installations\"]"
                        },
                        new
                        {
                            Id = "field-asset-id",
                            FieldType = "primary key",
                            IsActive = true,
                            Name = "Asset ID#",
                            SortOrder = 22,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-machine-id",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Machine ID",
                            SortOrder = 23,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-serial-number",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Serial Number",
                            SortOrder = 24,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-pm-count",
                            FieldType = "number",
                            IsActive = true,
                            Name = "PM Count",
                            SortOrder = 25,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-comments",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Comments",
                            SortOrder = 26,
                            TablesJson = "[\"assets\"]"
                        },
                        new
                        {
                            Id = "field-document",
                            FieldType = "file",
                            IsActive = true,
                            Name = "Document",
                            SortOrder = 27,
                            TablesJson = "[\"documents\"]"
                        },
                        new
                        {
                            Id = "field-document-type",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Document Type",
                            SortOrder = 28,
                            TablesJson = "[\"documents\"]"
                        },
                        new
                        {
                            Id = "field-linked-to",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Linked To",
                            SortOrder = 29,
                            TablesJson = "[\"documents\"]"
                        },
                        new
                        {
                            Id = "field-uploaded-at",
                            FieldType = "date",
                            IsActive = true,
                            Name = "Uploaded At",
                            SortOrder = 30,
                            TablesJson = "[\"documents\"]"
                        },
                        new
                        {
                            Id = "field-user-name",
                            FieldType = "text",
                            IsActive = true,
                            Name = "User Name",
                            SortOrder = 31,
                            TablesJson = "[\"users\"]"
                        },
                        new
                        {
                            Id = "field-email",
                            FieldType = "email",
                            IsActive = true,
                            Name = "Email",
                            SortOrder = 32,
                            TablesJson = "[\"users\"]"
                        },
                        new
                        {
                            Id = "field-role",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Role",
                            SortOrder = 33,
                            TablesJson = "[\"users\"]"
                        },
                        new
                        {
                            Id = "field-active",
                            FieldType = "checkbox",
                            IsActive = true,
                            Name = "Active",
                            SortOrder = 34,
                            TablesJson = "[\"users\"]"
                        },
                        new
                        {
                            Id = "field-site-address",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Address",
                            SortOrder = 35,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-site-city",
                            FieldType = "text",
                            IsActive = true,
                            Name = "City",
                            SortOrder = 36,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-site-state",
                            FieldType = "text",
                            IsActive = true,
                            Name = "State",
                            SortOrder = 37,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-site-country",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Country",
                            SortOrder = 38,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-site-zipcode",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Zip Code",
                            SortOrder = 39,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-site-contact-name",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Contact Name",
                            SortOrder = 40,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-site-contact-phone",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Contact Phone",
                            SortOrder = 41,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-site-contact-email",
                            FieldType = "email",
                            IsActive = true,
                            Name = "Contact Email",
                            SortOrder = 42,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-site-notes",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Notes",
                            SortOrder = 43,
                            TablesJson = "[\"sites\"]"
                        },
                        new
                        {
                            Id = "field-customer-id",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Customer ID",
                            SortOrder = 44,
                            TablesJson = "[\"customers\"]"
                        },
                        new
                        {
                            Id = "field-customer-industry",
                            FieldType = "text",
                            IsActive = true,
                            Name = "Industry",
                            SortOrder = 45,
                            TablesJson = "[\"customers\"]"
                        },
                        new
                        {
                            Id = "field-customer-key",
                            FieldType = "primary key",
                            IsActive = true,
                            Name = "Customer Key",
                            SortOrder = 46,
                            TablesJson = "[\"customers\"]"
                        },
                        new
                        {
                            Id = "field-site-key",
                            FieldType = "primary key",
                            IsActive = true,
                            Name = "Site Key",
                            SortOrder = 47,
                            TablesJson = "[\"sites\"]"
                        });
                });

            modelBuilder.Entity("Commtrac.Api.Models.FieldValueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldDefinitionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("TableName", "EntityId");

                    b.ToTable("FieldValues");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InspectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inspector")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduledDate")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InspectionPhotoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InspectionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("InspectionPhotos");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InstallationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualFinish")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualStart")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUsers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("CustomerSignOffContact")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerSignOffDate")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallerNotes")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pm1Serial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pm2Serial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pm3Serial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pm4Serial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledEnd")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledStart")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteContactName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteContactPhone")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InstallationTabEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstallationTabs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.InstallationTabRowEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstallationTabRows");
                });

            modelBuilder.Entity("Commtrac.Api.Models.IssueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Commtrac.Api.Models.NotificationSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrontendBaseUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmsApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmsProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmsSender")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpFrom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPass")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Commtrac.Api.Models.OfficeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("Commtrac.Api.Models.FeatureEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("SubPropertiesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("text");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Commtrac.Api.Models.FeatureDependencyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptureFieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<decimal>("DefaultQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1m);

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureDependencies");
                });

            modelBuilder.Entity("Commtrac.Api.Models.ProductFeatureEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("Commtrac.Api.Models.DivisionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(99);

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("Commtrac.Api.Models.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Commtrac.Api.Models.ProjectAssetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AsBuiltJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetModel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUserId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigLabel")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductConfigId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowTemplateId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductConfigId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectAssets");
                });

            modelBuilder.Entity("Commtrac.Api.Models.ProjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalDecision")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ContractValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishDate")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationMode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInstallationProject")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowMode")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbabilityStage")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductFeatureValuesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("ProductIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectManager")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Commtrac.Api.Models.QuickbaseSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationsFieldMapJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("InstallationsTableId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectsFieldMapJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("ProjectsTableId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmHostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuickbaseSettings");
                });

            modelBuilder.Entity("Commtrac.Api.Models.RoleConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleConfigs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Commtrac.Api.Models.SiteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Commtrac.Api.Models.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is2faEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryCodesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Commtrac.Api.Models.WorkInstructionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureValuesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Summary")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WorkInstructions");
                });

            modelBuilder.Entity("Commtrac.Api.Models.WorkInstructionTemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureSelectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowTemplateId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkInstructionTemplates");
                });

            modelBuilder.Entity("Commtrac.Api.Models.WorkOrderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectAssetId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsDataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowTemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("Commtrac.Api.Models.WorkflowConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureSelectionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("MediaJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("TemplateSourceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Status");

                    b.ToTable("WorkflowConfigs");
                });

            modelBuilder.Entity("Commtrac.Api.Models.WorkflowConfigFeatureEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InclusionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("WorkflowConfigId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("WorkflowConfigId");

                    b.ToTable("WorkflowConfigFeatures");
                });

            modelBuilder.Entity("Commtrac.Api.Models.WorkflowTemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WorkflowTemplates");
                });

            modelBuilder.Entity("Commtrac.Api.Models.WorkflowTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkflowTypes");

                    b.HasData(
                        new
                        {
                            Id = "wftype-installation",
                            IsActive = true,
                            Name = "Installation",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "wftype-commissioning",
                            IsActive = true,
                            Name = "Commissioning",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "wftype-inspection",
                            IsActive = true,
                            Name = "Inspection",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "wftype-repair",
                            IsActive = true,
                            Name = "Repair",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("Commtrac.Api.Models.InspectionImportEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("LOCAL");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("RECEIVED");

                    b.Property<string>("ErrorText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MappedRunId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");
                    b.HasIndex("AssetId");
                    b.HasIndex("ContentHash");
                    b.HasIndex("Status");

                    b.ToTable("InspectionImports");
                });
#pragma warning restore 612, 618
        }
    }
}
